package com.zzlcoding.capacitor.plugin.sensors;

import android.hardware.Sensor;

public enum SensorType {
    PROXIMITY(Sensor.TYPE_PROXIMITY),
    ACCELEROMETER(Sensor.TYPE_ACCELEROMETER),
    GRAVITY(Sensor.TYPE_GRAVITY),
    GYROSCOPE(Sensor.TYPE_GYROSCOPE),
    GYROSCOPE_UNCALIBRATED(Sensor.TYPE_GYROSCOPE_UNCALIBRATED),
    LINEAR_ACCELERATION(Sensor.TYPE_LINEAR_ACCELERATION),
    ROTATION_VECTOR(Sensor.TYPE_ROTATION_VECTOR),
    STEP_COUNTER(Sensor.TYPE_STEP_COUNTER),
    GAME_ROTATION_VECTOR(Sensor.TYPE_GAME_ROTATION_VECTOR),
    GEOMAGNETIC_ROTATION_VECTOR(Sensor.TYPE_GEOMAGNETIC_ROTATION_VECTOR),
    MAGNETIC_FIELD(Sensor.TYPE_MAGNETIC_FIELD),
    MAGNETIC_FIELD_UNCALIBRATED(Sensor.TYPE_MAGNETIC_FIELD_UNCALIBRATED),
    ORIENTATION(Sensor.TYPE_ORIENTATION),
    AMBIENT_TEMPERATURE(Sensor.TYPE_AMBIENT_TEMPERATURE),
    LIGHT(Sensor.TYPE_LIGHT),
    PRESSURE(Sensor.TYPE_PRESSURE),
    RELATIVE_HUMIDITY(Sensor.TYPE_RELATIVE_HUMIDITY),
    TEMPERATURE(Sensor.TYPE_AMBIENT_TEMPERATURE),
    ALL(Sensor.TYPE_ALL),
    UNKNOWN(-2);

    private int value;

    SensorType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
